stages:
  - dockerize

variables:
  REGISTRY: "artifactory-c4.bt.local/tne-registry"
  IMAGE_NAME: "speaches"
  PLATFORMS: "linux/amd64,linux/arm64"

.build-and-push-template:
  stage: dockerize
  image:
    name: "gcr.io/kaniko-project/executor:debug"
    entrypoint: [""]
  script:
    - echo "Logging in to registry"
    - echo "$CI_JOB_TOKEN" | docker login "$REGISTRY" -u gitlab-ci-token --password-stdin
    - >
      /kaniko/executor
      --context "$CI_PROJECT_DIR"
      --dockerfile "$CI_PROJECT_DIR/Dockerfile"
      --destination "$REGISTRY/$IMAGE_NAME:$CI_COMMIT_REF_SLUG-cuda"
      --destination "$REGISTRY/$IMAGE_NAME:latest-cuda"
      --cache=true
      --cache-repo="$REGISTRY/$IMAGE_NAME-cache"
      --build-arg "BASE_IMAGE=nvidia/cuda:12.9.0-cudnn-runtime-ubuntu24.04"
      --cache-copy-layers
      --platform="$PLATFORMS"
      --no-push
