stages:
  - dockerize
#  - deploy

variables:
  APP: speaches
  IMAGE: $AWS_REGISTRY/$APP # Image repository in AWS ECR
  AWS_DEFAULT_REGION: ap-south-1
  BUILD: $CI_PIPELINE_IID
  DOCKER_REPO: cellular-docker.aldar-artifactory.internal
  DOCKER_REPO_NAME: tne
  IMAGE_LOCAL: $DOCKER_REPO/$DOCKER_REPO_NAME/$APP

build-image:
  stage: dockerize
  tags: ["aldar-cellular"]
  extends: .build_and_push_image
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - |
      buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --local context=. \
        --local dockerfile=. \
        --opt build-arg:BASE_IMAGE=ubuntu:24.04 \
        --export-cache type=registry,ref=$IMAGE:buildcache \
        --import-cache type=registry,ref=$IMAGE:buildcache \
        --output type=image,name=$IMAGE:$TAG,push=true

#dev:
#  extends: .deployment
#  environment: dev
#
#staging:
#  extends: .deployment
#  environment: staging
#
#uat:
#  extends: .deployment
#  environment: uat

.build_and_push_image:
  stage: push
  image:
    name: $DOCKER_REPO/$DOCKER_REPO_NAME/tne-aws-buildkit-ecr-helper:1.0
    entrypoint: [""]

#.deployment:
#  stage: deploy
#  extends: .dind
#  image: artifactory-c4.bt.local/c4i-registry/pipeline:1.2.0
#  dependencies:
#    - build-image
#  script:
#    - | # SSH/SCP into the GPU server and update version
#    - apt update
#    - apt install -y sshpass
#    - |
#      sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no -tt $SSH_USER@$SERVER '
#        cd phobos-ai
#        echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin artifactory-c4.bt.local
#        docker compose pull
#        docker compose up -d
#      '
#  when: manual
#  allow_failure: true