stages:
  - prepare
  - dockerize
  - deploy

variables:
  CI_REGISTRY: "artifactory-c4.bt.local/tne-registry"
  IMAGE_NAME: "speaches"

prepare-sdk:
  image: $CI_REGISTRY/ai-cicd:357cbf3a
  stage: prepare
  script:
    - echo "Extracting version..."
    - PYPROJECT_VERSION=$(python -c "import toml; print(toml.load('${CI_PROJECT_DIR}/pyproject.toml')['project']['version'])")
    - echo "PYPROJECT_VERSION=$PYPROJECT_VERSION" >> version.env
  artifacts:
    reports:
      dotenv:
        - version.env

build-image:
  stage: dockerize
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "Building image with Kaniko"
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}
      --dockerfile "$CI_PROJECT_DIR/Dockerfile"
      --destination "$CI_REGISTRY/$IMAGE_NAME:$CI_COMMIT_REF_SLUG-cpu"
      --destination $CI_REGISTRY/$IMAGE_NAME:$PYPROJECT_VERSION
      --destination "$CI_REGISTRY/$IMAGE_NAME:latest-cpu"
      --cache=true
      --cache-repo=$CI_REGISTRY/$IMAGE_NAME-cache
      --build-arg "BASE_IMAGE=ubuntu:24.04"
      --cache-copy-layers

dev:
  extends: .deployment
  environment: dev

staging:
  extends: .deployment
  environment: staging

uat:
  extends: .deployment
  environment: uat

.dind:
  services:
    - name: docker:dind
  variables:
    # Instruct Testcontainers to use the daemon of DinD.
    DOCKER_HOST: 'tcp://docker:2375'
    DOCKER_TLS_CERTDIR: ''
    DOCKER_DRIVER: overlay2 # Improve performance with overlayfs.

.deployment:
  stage: deploy
  extends: .dind
  image: artifactory-c4.bt.local/c4i-registry/pipeline:1.2.0
  dependencies:
    - build-image
  script:
    - | # SSH/SCP into the GPU server and update version
    - apt update
    - apt install -y sshpass
    - |
      sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no -tt $SSH_USER@$SERVER '
        cd phobos-ai
        echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin artifactory-c4.bt.local
        docker compose pull
        docker compose up -d
      '
  when: manual
  allow_failure: true