services:
  speaches:
    container_name: speaches
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - ALLOW_ORIGINS=["http://localhost:9000"]
      - ENABLE_UI=False
      - HF_TOKEN=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
      - PYANNOTE_METRICS_ENABLED=0
      - PYTHONDEBUG=1
      - PYTHONUNBUFFERED=1
    develop:
      watch:
        - action: rebuild
          path: ./uv.lock
        - action: sync+restart
          path: ./src
          target: /home/ubuntu/speaches/src
    env_file:
      - path: .env
        required: false
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://0.0.0.0:8000/health"] # TODO: won't work if a user changes the port
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
